onlyBuiltDependencies:
  - edgedriver
  - esbuild
  - geckodriver
  - msw
  - protobufjs

overrides:
  'ajv@^8': '^8.18.0'
  'diff@^7': '^8.0.3'
  'lodash@^4': '^4.18.1'
  'minimatch@^10': '^10.2.3'
  'serialize-javascript@^6': '^7.0.5'

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - minimatch
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'
  - vite # Remove after 2026-04-10.
  - vitest # Remove after 2026-04-10.
  - '@vitest/*' # Remove after 2026-04-10.

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
