onlyBuiltDependencies:
  - edgedriver
  - esbuild
  - geckodriver
  - msw
  - protobufjs

overrides:
  'ajv@^8': '^8.18.0'
  'diff@^7': '^8.0.3'
  'minimatch@^10': '^10.2.3'
  'serialize-javascript@^6': '^7.0.3'

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - minimatch
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
