onlyBuiltDependencies:
  - edgedriver
  - esbuild
  - geckodriver
  - msw
  - protobufjs

overrides:
  '@smithy/config-resolver@^3.0.0': '^4.4.0'
  'ajv@^8': '^8.18.0'
  'diff@^7': '^8.0.3'
  'esbuild': '^0.25.0'
  'minimatch@^10': '^10.2.3'
  'minimatch@^5': '^5.1.8'
  'minimatch@^9': '^9.0.7'

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - minimatch
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
